export const popularGenres = [
  "Biography",
  "Business",
  "Children",
  "Contemporary Fiction",
  "Comedy",
  "Fantasy",
  "Fantastic",
  "Fiction",
  "Historical Fiction",
  "History",
  "Horror",
  "Literary Fiction",
  "Memoir",
  "Mystery",
  "Philosophy",
  "Poetry",
  "Politics",
  "Romance",
  "Science",
  "Science Fiction",
  "Self-Help",
  "Thriller",
  "Young Adult"
];